### ISSUE TITLE
problem with using migrate

### ISSUE THREAD

**Issue by Nedapapen** [SAY-DAO/ngo-panel-v2#4]
on my phone i can see the children list but they are not selectable, and by clicking on "migrate" button without selecting any child, there appears a "network error" 
(i was trying to migrate "Negar" from SW004 to SW027)

on my desktop the migrate page dose not even get loaded.
![WhatsApp Image 2022-09-19 at 1 04 37 PM](https://user-images.githubusercontent.com/79936921/190980202-c7c7c4b1-37de-4028-b78a-d0423e6b5d44.jpeg)

**Comment by ehsan-g** [comment]
Fixed!
