### ISSUE TITLE
adding new NGO

### ISSUE THREAD

**Issue by Nedapapen** [SAY-DAO/ngo-panel-v2#5]
I can not add New NGOs ,
By clicking on "+ Add" in the NGOs drop down, a form opens, after filling the form, i clicked on "update" button but noting happened, i did not even received any error.

**Comment by ehsan-g** [comment]
@Nedapapen I added the error response. I think you were missing some input fields. Please try now.

**Comment by Nedapapen** [comment]
@ehsan-g  jan i have 1point and one problem, 
all fields should not be mandatory i think
and i received this error while i have selected the city
![errorr](https://user-images.githubusercontent.com/79936921/192098457-b008d017-5a92-40c0-88fa-cadeab39a7ca.png)

**Comment by ehsan-g** [comment]
@neda done
All fields are required and they are set from backend but I changed couple of other bugs now you can do both add and Delete
